/**
 * A pinned snapshot of exposure scores over a fixed set of documents.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * WHY THIS EXISTS (the D24 gap)
 *
 * The exposure score is assembled from numbers that live in several files and
 * were each chosen for a reason local to that file: severity weights and type
 * factors in packages/data, the SPECIFICITY table in fuse/resolve.ts, the
 * saturation curve in exposure/index.ts. Every one of those is individually
 * defensible and individually editable.
 *
 * The failure mode is that someone edits SPECIFICITY to fix an overlap-
 * resolution bug — a completely legitimate change, made for a good reason,
 * with the overlap tests passing afterwards — and silently moves every
 * document's exposure score. Nothing fails. Nobody notices. The scores users
 * see, and the bands the review panel colours by, quietly mean something
 * different from the day they were calibrated.
 *
 * `exposure.test.ts` pins the engine's PROPERTIES: monotonicity, decomposition,
 * saturation. Properties survive a re-anchoring of the scale, which is exactly
 * why they cannot catch this. So this file pins the VALUES.
 *
 * WHAT A FAILURE HERE MEANS: not necessarily a bug. It means a change to one
 * of those tables moved the published scale, and that consequence has to be
 * looked at and acknowledged rather than absorbed. If the new numbers are
 * right, update the snapshot IN THE SAME COMMIT as the change that moved them,
 * so the diff shows both together and a reviewer can see what a one-line table
 * edit did to every document's score.
 *
 * The documents are held here rather than generated, so the input cannot drift
 * underneath the expectations and make a passing test meaningless.
 * ─────────────────────────────────────────────────────────────────────────
 */

import { describe, expect, it } from 'vitest';

import { computeExposure, exposureBand } from '../src/exposure/index.js';
import type { ExposureInput } from '../src/exposure/index.js';

/**
 * Fixed documents spanning the range the score has to discriminate across.
 *
 * Chosen so that a change to any one severity category moves at least one
 * document, and so that the ORDERING between documents is itself meaningful —
 * a re-anchoring that preserved every score's rank would still be caught by
 * the absolute values, and one that preserved the values but scrambled the
 * ranks would be caught by the ordering assertion below.
 */
const DOCUMENTS: ReadonlyArray<{ name: string; entities: readonly ExposureInput[] }> = [
  {
    name: 'empty',
    entities: [],
  },
  {
    name: 'a city mentioned in passing',
    entities: [{ type: 'LOCATION', calibratedConfidence: 0.82 }],
  },
  {
    name: 'a name and a city',
    entities: [
      { type: 'PERSON', calibratedConfidence: 0.91 },
      { type: 'LOCATION', calibratedConfidence: 0.78 },
    ],
  },
  {
    name: 'a support email with contact details',
    entities: [
      { type: 'PERSON', calibratedConfidence: 0.94 },
      { type: 'EMAIL', calibratedConfidence: 0.99 },
      { type: 'PHONE', calibratedConfidence: 0.88 },
      { type: 'STREET_ADDRESS', calibratedConfidence: 0.71 },
    ],
  },
  {
    name: 'a pasted stack trace with a leaked key',
    entities: [
      { type: 'API_KEY', calibratedConfidence: 0.97 },
      { type: 'CONNECTION_STRING', calibratedConfidence: 0.93 },
      { type: 'IP_ADDRESS', calibratedConfidence: 0.85 },
    ],
  },
  {
    name: 'an onboarding form: identity plus bank details',
    entities: [
      { type: 'PERSON', calibratedConfidence: 0.96 },
      { type: 'NATIONAL_ID', calibratedConfidence: 0.98 },
      { type: 'DATE_OF_BIRTH', calibratedConfidence: 0.9 },
      { type: 'IBAN', calibratedConfidence: 0.99 },
      { type: 'STREET_ADDRESS', calibratedConfidence: 0.8 },
    ],
  },
  {
    name: 'a medical referral',
    entities: [
      { type: 'PERSON', calibratedConfidence: 0.95 },
      { type: 'HEALTH_DATA', calibratedConfidence: 0.87 },
      { type: 'DATE_OF_BIRTH', calibratedConfidence: 0.92 },
      { type: 'NATIONAL_ID', calibratedConfidence: 0.94 },
    ],
  },
  {
    name: 'a low-confidence single postal code',
    entities: [{ type: 'POSTAL_CODE', calibratedConfidence: 0.34 }],
  },
];

/**
 * THE PINNED VALUES.
 *
 * Generated by running the engine and recorded verbatim — not hand-computed,
 * because a hand-computed expectation would be pinning arithmetic rather than
 * the engine. Their job is to change loudly, not to be independently derived.
 */
const EXPECTED: Readonly<Record<string, { score: number; band: string }>> = {
  empty: { score: 0, band: 'none' },
  'a low-confidence single postal code': { score: 7, band: 'low' },
  'a city mentioned in passing': { score: 19, band: 'low' },
  'a name and a city': { score: 40, band: 'moderate' },
  'a support email with contact details': { score: 77, band: 'severe' },
  'a pasted stack trace with a leaked key': { score: 82, band: 'severe' },
  'a medical referral': { score: 91, band: 'severe' },
  'an onboarding form: identity plus bank details': { score: 93, band: 'severe' },
};

describe('exposure score snapshot', () => {
  for (const document of DOCUMENTS) {
    it(`is stable for: ${document.name}`, () => {
      const report = computeExposure(document.entities);
      const expected = EXPECTED[document.name];
      expect(expected).toBeDefined();
      expect({
        score: Math.round(report.score),
        band: exposureBand(report.score),
      }).toEqual({ score: expected?.score, band: expected?.band });
    });
  }

  it('preserves the relative ordering of the fixed documents', () => {
    // Catches a re-anchoring that happened to leave the absolute values alone
    // but changed which kind of document outranks which — the thing a user
    // actually reads off the score.
    const scored = DOCUMENTS.map((d) => ({
      name: d.name,
      score: computeExposure(d.entities).score,
    })).sort((a, b) => a.score - b.score);

    expect(scored.map((s) => s.name)).toEqual([
      'empty',
      'a low-confidence single postal code',
      'a city mentioned in passing',
      'a name and a city',
      'a support email with contact details',
      'a pasted stack trace with a leaked key',
      'a medical referral',
      'an onboarding form: identity plus bank details',
    ]);
  });
});
