/**
 * protect.test.ts — the M12 entry point.
 *
 * The values here are GENERATED by core's own seeded generators rather than
 * written out. The first draft of the M12 smoke probe used
 * `4111111111111111` and `GB82 WEST 1234 5698 7654 32`, reported that nothing
 * at all was detected, and was wrong: both are canonical PUBLISHED test
 * values, and `creditCard.ts` lists the first in `TEST_CARDS` as "detected,
 * never masked" on purpose. A hand-picked constant is a chance to pick the one
 * value the engine is right to ignore — the same mistake M10 made with an
 * RFC 2606 reserved e-mail domain. The one exception is the test-PAN case
 * below, where the published value IS the subject of the test.
 */

import { describe, expect, it } from 'vitest';

import {
  ALL_ENTITY_TYPES,
  detectableEntityTypes,
  generate,
  protect,
  restore,
  toCalibrationModel,
  Vault,
  type NerRecognizer,
  type NerSpan,
} from '../src/index.js';
import { CALIBRATION_MODEL } from '@privacyshield/data';

/** A card and an IBAN that are valid, and are not published test vectors. */
function sensitiveText(seed: number): { text: string; pan: string; iban: string } {
  const pan = generate.generateValidCard(seed);
  // A different seed, or the two would be drawn from the same first draw of
  // the same stream and correlate across cases.
  const iban = generate.generateValidIban(seed ^ 0x5f5f);
  return { text: `Charge ${pan} and refund to ${iban} please.`, pan, iban };
}

describe('protect()', () => {
  it('finds, masks, and can restore', async () => {
    const { text, pan, iban } = sensitiveText(0xc0ffee);
    const result = await protect(text, { seed: 7 });

    expect(result.entities.map((e) => e.type).sort()).toEqual(['CREDIT_CARD', 'IBAN']);
    expect(result.maskedText).not.toContain(pan);
    expect(result.maskedText).not.toContain(iban);
    expect(restore(result.maskedText, result.vault).restoredText).toBe(text);
  });

  it('never leaves an original value in the masked text', async () => {
    // The property that matters most: whatever else is wrong, the thing we
    // were asked to remove must be gone.
    for (const seed of [1, 2, 3, 99, 12345]) {
      const { text, pan, iban } = sensitiveText(seed);
      const result = await protect(text, { seed });
      expect(result.maskedText, `seed ${String(seed)}`).not.toContain(pan);
      expect(result.maskedText, `seed ${String(seed)}`).not.toContain(iban);
    }
  });

  it('is deterministic for a fixed input and seed', async () => {
    const { text } = sensitiveText(4242);
    const a = await protect(text, { seed: 11 });
    const b = await protect(text, { seed: 11 });
    expect(a.maskedText).toBe(b.maskedText);
  });

  it('gives the same value the same surrogate across calls sharing a vault', async () => {
    const { text, pan } = sensitiveText(555);
    const vault = new Vault();
    const first = await protect(text, { seed: 3, vault });
    const second = await protect(`again: ${pan}`, { seed: 3, vault });

    const surrogateOf = (r: Awaited<ReturnType<typeof protect>>): string | undefined =>
      r.entities.find((e) => e.type === 'CREDIT_CARD')?.surrogate;

    expect(surrogateOf(first)).toBeDefined();
    expect(surrogateOf(second)).toBe(surrogateOf(first));
  });

  it('detects a published test PAN but does not mask it', async () => {
    // SPEC/creditCard.ts: "Known test card numbers matched but classified as
    // non-sensitive." The number must survive, because masking a documentation
    // example is a false positive the user pays for.
    const text = 'Docs example: 4111111111111111 is the Visa test PAN.';
    const result = await protect(text, { seed: 1 });
    expect(result.maskedText).toContain('4111111111111111');
    expect(result.entities.some((e) => e.type === 'CREDIT_CARD')).toBe(false);
  });

  describe('stagesRun is derived, not declared', () => {
    it('omits stage2-ner when no recogniser is passed', async () => {
      const { text } = sensitiveText(8);
      const result = await protect(text, { seed: 1 });
      expect(result.stagesRun).not.toContain('stage2-ner');
      expect(result.stagesRun).toContain('stage1-validated-identifier');
    });

    it('includes stage2-ner when one is', async () => {
      const silent: NerRecognizer = {
        id: 'test-silent',
        warmup: () => Promise.resolve(),
        recognize: () => Promise.resolve([] as NerSpan[]),
      };
      const { text } = sensitiveText(9);
      const result = await protect(text, { seed: 1, ner: silent });
      expect(result.stagesRun).toContain('stage2-ner');
    });
  });

  it('fails closed: a broken recogniser throws rather than reporting nothing', async () => {
    // SPEC.md's second non-negotiable. A caller must not be able to mistake a
    // failure for a clean document, so the rejection has to escape.
    const broken: NerRecognizer = {
      id: 'test-broken',
      warmup: () => Promise.resolve(),
      recognize: () => Promise.reject(new Error('model unavailable')),
    };
    const { text } = sensitiveText(10);
    await expect(protect(text, { seed: 1, ner: broken })).rejects.toThrow('model unavailable');
  });

  it('applies typeAllowed before a surrogate is minted', async () => {
    const { text, pan } = sensitiveText(77);
    const result = await protect(text, { seed: 1, typeAllowed: (t) => t !== 'CREDIT_CARD' });
    expect(result.entities.some((e) => e.type === 'CREDIT_CARD')).toBe(false);
    // Excluded means NOT MASKED, which is the honest consequence of the toggle
    // and the reason the panel shows what it skipped.
    expect(result.maskedText).toContain(pan);
  });

  it("rejects profile 'custom' with a message that says what to pass", async () => {
    await expect(protect('hello', { profile: 'custom' })).rejects.toThrow(/SensitivityProfile/);
  });

  it('scores exposure above zero when something sensitive is found', async () => {
    const { text } = sensitiveText(31);
    const result = await protect(text, { seed: 1 });
    expect(result.exposure.score).toBeGreaterThan(0);
  });

  it('reports nothing and masks nothing for ordinary prose', async () => {
    const result = await protect('The meeting is on Tuesday in the small room.', { seed: 1 });
    expect(result.entities).toEqual([]);
    expect(result.maskedText).toBe('The meeting is on Tuesday in the small room.');
    expect(result.exposure.score).toBe(0);
  });
});

describe('the entity type enumeration', () => {
  it('lists every EntityType member', () => {
    expect(ALL_ENTITY_TYPES.length).toBe(35);
    expect(new Set(ALL_ENTITY_TYPES).size).toBe(ALL_ENTITY_TYPES.length);
  });

  it('derives the detectable set from the registry, and excludes DATE_OF_BIRTH', () => {
    // M11 found this by counting types while writing the README; nothing in
    // the suite could catch it, because every test agreed with the code. It is
    // derived here so the answer cannot go stale.
    const detectable = detectableEntityTypes();
    expect(detectable).not.toContain('DATE_OF_BIRTH');
    expect(detectable.length).toBe(ALL_ENTITY_TYPES.length - 1);
  });

  it('agrees with the count the options page pins', () => {
    // packages/extension/scripts/verify-options.py asserts 34 checkboxes.
    expect(detectableEntityTypes().length).toBe(34);
  });
});

describe('the shipped calibration model', () => {
  it('has no per-type key that is not an EntityType', () => {
    // The `as unknown as CalibrationModel` cast this replaced would have hidden
    // a stale key, and calibration would silently fall back to the pooled curve
    // for that type forever.
    expect(toCalibrationModel(CALIBRATION_MODEL).unknownTypes).toEqual([]);
  });
});
