/**
 * The fitted Stage 4 CALIBRATION MODEL.
 *
 * GENERATED by `node packages/eval/dist/bench/calibration.js --fit 2000
 * --eval 2000`, then committed — on the same terms as the other generated
 * data. Consumers must never fit a curve at runtime: the extension has no
 * corpus to fit one against, and a curve fitted on whatever the user happens
 * to have pasted would mean nothing.
 *
 * Isotonic regression per entity type. See ARCHITECTURE.md D23 for the method
 * and why isotonic rather than Platt, and BENCHMARKS.md for the reliability
 * curve measured on held-out documents.
 *
 * Fitted on 2620 documents, seeds 5904129/5904130, and evaluated on
 * documents PROVED disjoint from those rather than assumed to be — seed
 * separation alone was not sufficient, because templated hard negatives
 * collide across seeds.
 *
 * A step reads: candidates whose raw score fell in [from, to) were correct
 * `precision` of the time, over `samples` observations. That is the entire
 * model, and it can be checked by hand against the published table.
 */

/** One step of a fitted curve: scores in [from, to) map to `precision`. */
export interface CalibrationBinData {
  readonly from: number;
  readonly to: number;
  readonly precision: number;
  readonly samples: number;
}

export interface CalibrationCurveData {
  readonly bins: readonly CalibrationBinData[];
  readonly samples: number;
}

export interface CalibrationModelData {
  readonly perType: Readonly<Record<string, CalibrationCurveData>>;
  readonly pooled: CalibrationCurveData;
  readonly fittedOn: string;
}

export const CALIBRATION_MODEL: CalibrationModelData = {
  "perType": {
    "API_KEY": {
      "bins": [
        {
          "from": 0.8,
          "to": 1,
          "precision": 0.979296066252588,
          "samples": 483
        }
      ],
      "samples": 483
    },
    "HEALTH_DATA": {
      "bins": [
        {
          "from": 0.3,
          "to": 0.4,
          "precision": 0,
          "samples": 6
        },
        {
          "from": 0.6,
          "to": 0.7,
          "precision": 0.9888641425389755,
          "samples": 449
        }
      ],
      "samples": 455
    },
    "PHONE": {
      "bins": [
        {
          "from": 0.8,
          "to": 0.9,
          "precision": 1,
          "samples": 80
        },
        {
          "from": 0.9,
          "to": 1,
          "precision": 1,
          "samples": 552
        }
      ],
      "samples": 632
    },
    "CRYPTO_WALLET": {
      "bins": [
        {
          "from": 0.6,
          "to": 0.7,
          "precision": 1,
          "samples": 138
        },
        {
          "from": 0.8,
          "to": 0.9,
          "precision": 1,
          "samples": 192
        },
        {
          "from": 0.9,
          "to": 1,
          "precision": 1,
          "samples": 243
        }
      ],
      "samples": 573
    },
    "EMAIL": {
      "bins": [
        {
          "from": 0.8,
          "to": 0.9,
          "precision": 0.8345323741007195,
          "samples": 139
        },
        {
          "from": 0.9,
          "to": 1,
          "precision": 0.970873786407767,
          "samples": 515
        }
      ],
      "samples": 654
    },
    "NATIONAL_ID": {
      "bins": [
        {
          "from": 0.3,
          "to": 0.6,
          "precision": 0.037037037037037035,
          "samples": 27
        },
        {
          "from": 0.6,
          "to": 0.7,
          "precision": 0.48333333333333334,
          "samples": 120
        },
        {
          "from": 0.7,
          "to": 1,
          "precision": 0.942,
          "samples": 500
        }
      ],
      "samples": 647
    },
    "IP_ADDRESS": {
      "bins": [
        {
          "from": 0.6,
          "to": 0.7,
          "precision": 1,
          "samples": 4
        },
        {
          "from": 0.8,
          "to": 0.9,
          "precision": 1,
          "samples": 105
        },
        {
          "from": 0.9,
          "to": 1,
          "precision": 1,
          "samples": 125
        }
      ],
      "samples": 234
    },
    "TAX_ID": {
      "bins": [
        {
          "from": 0.6,
          "to": 0.7,
          "precision": 0.3088235294117647,
          "samples": 68
        },
        {
          "from": 0.8,
          "to": 0.9,
          "precision": 0.6923076923076923,
          "samples": 78
        },
        {
          "from": 0.9,
          "to": 1,
          "precision": 0.9682539682539683,
          "samples": 63
        }
      ],
      "samples": 209
    }
  },
  "pooled": {
    "bins": [
      {
        "from": 0.3,
        "to": 0.6,
        "precision": 0.6694915254237288,
        "samples": 118
      },
      {
        "from": 0.6,
        "to": 0.7,
        "precision": 0.8783505154639175,
        "samples": 970
      },
      {
        "from": 0.7,
        "to": 0.9,
        "precision": 0.950625,
        "samples": 1600
      },
      {
        "from": 0.9,
        "to": 1,
        "precision": 0.9745022703457912,
        "samples": 2863
      }
    ],
    "samples": 5551
  },
  "fittedOn": "2620 documents, seeds 5904129/5904130"
};
