/**
 * The weighted modular sum — the single algorithm behind most national
 * identifier check digits.
 *
 * SPEC.md calls for implementing each algorithm once and reusing it: "Many
 * national IDs are the same algorithm with different weights." That is
 * precisely true of this family. Turkey's TCKN, Poland's PESEL, Brazil's CPF,
 * China's RIC, Singapore's NRIC, Australia's TFN and dozens of others are all
 *
 *     Σ(digitᵢ × weightᵢ) mod m
 *
 * differing only in the weight vector, the modulus, and how the remainder is
 * turned back into an expected check character.
 *
 * DESIGN NOTE. This module deliberately stops at the remainder rather than
 * trying to model every "and then…" rule as configuration. The final step
 * varies too much to generalize honestly — some schemes use the remainder
 * directly, some its complement, some map 10→'X', some declare 10 invalid,
 * some subtract from 11 and fold both 10 and 11 to 0. Encoding all of that in
 * one options object produces a function nobody can read and whose branches
 * are individually untested. Each detector applies its own documented final
 * rule to the remainder this module returns. The shared, error-prone part —
 * the weighted sum itself — is written and tested exactly once.
 */

/**
 * Σ(digitᵢ × weightᵢ).
 *
 * Returns `null` when there are fewer weights than digits, which is always a
 * programming error rather than bad user input. Extra trailing weights are
 * ignored so a scheme can declare the full weight vector including the check
 * position and pass only the payload digits.
 */
export function weightedSum(digits: readonly number[], weights: readonly number[]): number | null {
  if (weights.length < digits.length) return null;
  let sum = 0;
  for (let i = 0; i < digits.length; i++) {
    sum += digits[i]! * weights[i]!;
  }
  return sum;
}

/**
 * Σ(digitᵢ × weightᵢ) mod `modulus`.
 *
 * Returns `null` on a weight/digit length mismatch or a non-positive modulus.
 */
export function weightedMod(
  digits: readonly number[],
  weights: readonly number[],
  modulus: number,
): number | null {
  if (modulus <= 0) return null;
  const sum = weightedSum(digits, weights);
  if (sum === null) return null;
  return sum % modulus;
}

/**
 * Σ(digitᵢ × weightᵢ) mod `modulus`, where the weight for position i is
 * generated by a function rather than read from a table.
 *
 * Several schemes define weights positionally — China's RIC uses 2^(n-i) mod
 * 11, ISO 7064 uses a running product — where writing the vector out would be
 * both longer and easier to get wrong than stating the rule.
 */
export function weightedModBy(
  digits: readonly number[],
  weightAt: (index: number) => number,
  modulus: number,
): number | null {
  if (modulus <= 0) return null;
  let sum = 0;
  for (let i = 0; i < digits.length; i++) {
    sum += digits[i]! * weightAt(i);
  }
  return sum % modulus;
}

/**
 * A cycling weight vector: position i uses `weights[i % weights.length]`.
 *
 * Used by schemes whose weights repeat over a long identifier (Russia's INN
 * and SNILS, several VAT formats) rather than being listed per position.
 */
export function cyclicWeightedMod(
  digits: readonly number[],
  weights: readonly number[],
  modulus: number,
): number | null {
  if (modulus <= 0 || weights.length === 0) return null;
  let sum = 0;
  for (let i = 0; i < digits.length; i++) {
    sum += digits[i]! * weights[i % weights.length]!;
  }
  return sum % modulus;
}

/**
 * The common "complement" closing rule: `(modulus − (sum mod modulus)) mod
 * modulus`.
 *
 * Extracted because getting the outer `mod` wrong is the classic bug — when
 * the remainder is 0 the complement must be 0, not `modulus`.
 */
export function complement(sum: number, modulus: number): number {
  return (modulus - (sum % modulus)) % modulus;
}
