/**
 * Transform 5: DECIMAL DIGIT FOLDING.
 *
 * Every Unicode decimal digit is folded to its ASCII equivalent: Arabic-Indic
 * ٠١٢, Extended Arabic-Indic ۰۱۲, Devanagari ०१२, Bengali ০১২, Thai ๐๑๒,
 * Tamil, Telugu, Myanmar, Khmer, and the rest.
 *
 * WHY THIS EXISTS. NFKC folds FULLWIDTH digits, because those are
 * compatibility variants of ASCII — but Arabic-Indic and Devanagari digits are
 * not compatibility variants of anything. They are the ordinary digits of
 * living scripts, and NFKC leaves them exactly as they are, correctly.
 *
 * The consequence for this pipeline was silent un-redaction. Every Stage 1
 * detector matches `\d` or an explicit `[0-9]` class, so before this transform
 * existed a Turkish national identity number written `٣٠٢١٤٥٦٤٦٤١٢`, an
 * Iranian phone number in Extended Arabic-Indic, a Hindi Aadhaar number in
 * Devanagari, a Thai national ID and a Bengali credit card were ALL reported
 * as clean documents — measured, not assumed. That is the same class of
 * failure as an identifier hidden inside HTML markup, and it landed on
 * precisely the Arabic, Persian, Urdu, Hindi, Bengali and Thai users the
 * multilingual work exists to serve.
 *
 * WHERE IT RUNS, and why last. After homoglyph folding, not before. Folding
 * digits changes a token's script census — Arabic-Indic digits are Arabic,
 * ASCII digits are not — so folding them earlier would alter the
 * dominant-script decision that homoglyph folding depends on, and could flip
 * a fold that D3 deliberately declines to make. Running afterwards leaves
 * that decision on the original scripts. ASCII digits are NFKC-stable, so no
 * further normalization pass is owed.
 *
 * THE USER'S TEXT IS NOT REWRITTEN. Folding happens in the NORMALIZED text
 * only; masking edits the ORIGINAL through the offset map, so a Persian user
 * sees their own digits back. That separation is the entire point of the
 * offset-map contract.
 */

import { MappedTextBuilder, type StepChange, type TransformStepResult } from '../offsetMap.js';

/**
 * The first code point of every Unicode decimal-digit block.
 *
 * Each block is ten consecutive code points whose first has value zero, so a
 * digit's value is `codePoint - blockZero`. Generated by scanning the whole
 * code space for `\p{Nd}` runs of ten; 72 blocks in the Unicode version
 * shipped with the runtime. Sorted, which `blockZeroFor` relies on.
 */
const DIGIT_BLOCK_ZEROS: readonly number[] = [
  0x30, 0x660, 0x6f0, 0x7c0, 0x966, 0x9e6, 0xa66, 0xae6,
  0xb66, 0xbe6, 0xc66, 0xce6, 0xd66, 0xde6, 0xe50, 0xed0,
  0xf20, 0x1040, 0x1090, 0x17e0, 0x1810, 0x1946, 0x19d0, 0x1a80,
  0x1a90, 0x1b50, 0x1bb0, 0x1c40, 0x1c50, 0xa620, 0xa8d0, 0xa900,
  0xa9d0, 0xa9f0, 0xaa50, 0xabf0, 0xff10, 0x104a0, 0x10d30, 0x10d40,
  0x11066, 0x110f0, 0x11136, 0x111d0, 0x112f0, 0x11450, 0x114d0, 0x11650,
  0x116c0, 0x116d0, 0x11730, 0x118e0, 0x11950, 0x11bf0, 0x11c50, 0x11d50,
  0x11da0, 0x11de0, 0x11f50, 0x16130, 0x16a60, 0x16ac0, 0x16b50, 0x16d70,
  0x1ccf0, 0x1d7ce, 0x1e140, 0x1e2f0, 0x1e4f0, 0x1e5f1, 0x1e950, 0x1fbf0,
];

/** ASCII '0', whose block is skipped: it is already what we fold to. */
const ASCII_ZERO = 0x30;

/**
 * The zero of the decimal-digit block containing `codePoint`, or undefined.
 * Binary search over the sorted block list.
 */
function blockZeroFor(codePoint: number): number | undefined {
  let low = 0;
  let high = DIGIT_BLOCK_ZEROS.length - 1;
  while (low <= high) {
    const mid = (low + high) >> 1;
    const zero = DIGIT_BLOCK_ZEROS[mid]!;
    if (codePoint < zero) high = mid - 1;
    else if (codePoint > zero + 9) low = mid + 1;
    else return zero;
  }
  return undefined;
}

/** The ASCII digit for a code point, or undefined if it is not a decimal digit. */
export function asciiDigitFor(codePoint: number): string | undefined {
  const zero = blockZeroFor(codePoint);
  if (zero === undefined || zero === ASCII_ZERO) return undefined;
  return String.fromCharCode(ASCII_ZERO + (codePoint - zero));
}

/**
 * Fold every non-ASCII decimal digit to ASCII.
 *
 * Most blocks are BMP and fold one code unit to one, leaving offsets
 * untouched. A few are astral (Osmanya, Brahmi, mathematical digits) and fold
 * a surrogate PAIR to a single character, so this is not a 1:1 transform and
 * goes through `MappedTextBuilder` rather than assuming equal lengths — the
 * same machinery NFKC's expansions use.
 */
export function foldDigits(text: string): TransformStepResult | null {
  // Fast path: the overwhelming majority of text has no non-ASCII digit, and
  // must not pay for a builder or a map.
  let first = -1;
  for (let i = 0; i < text.length; i += 1) {
    const cp = text.codePointAt(i)!;
    if (cp > 0xffff) i += 1;
    if (cp !== ASCII_ZERO && asciiDigitFor(cp) !== undefined) {
      first = i - (cp > 0xffff ? 1 : 0);
      break;
    }
  }
  if (first === -1) return null;

  const builder = new MappedTextBuilder();
  const changes: StepChange[] = [];
  let cursor = 0;

  for (let i = first; i < text.length; i += 1) {
    const codePoint = text.codePointAt(i)!;
    const width = codePoint > 0xffff ? 2 : 1;
    const replacement = asciiDigitFor(codePoint);
    if (replacement === undefined) {
      i += width - 1;
      continue;
    }

    builder.copyVerbatim(text, cursor, i);
    builder.replaceRange(replacement, i, i + width);
    changes.push({
      kind: 'fold-digits',
      start: i,
      end: i + width,
      before: text.slice(i, i + width),
      after: replacement,
    });
    cursor = i + width;
    i += width - 1;
  }

  builder.copyVerbatim(text, cursor, text.length);
  const { text: out, map } = builder.finish(text.length);
  return { text: out, map, changes };
}
